
ifndef SAMMYOSROOT
    $(error Please set SAMMYOSROOT to the root directory.)
endif

INCLUDE = -I$(SAMMYOSROOT)/libc -I$(SAMMYOSROOT)
CFLAGS = -g -std=gnu99 -ffreestanding -Wall -Wextra -O0 $(INCLUDE)
LINKER_FLAGS = -ffreestanding -O0 -nostdlib -nostdinc
