
ifndef SAMMYOSROOT
    $(error Please set SAMMYOSROOT to the root directory)
endif

ifndef SAMMYOSARCH
    $(error Please set SAMMYOSARCH to the target architecture)
    $(error Supported architectures: i386)
endif

BUILD_DIR = ${SAMMYOSROOT}/_out

INCLUDE = -I$(SAMMYOSROOT)/libc/include -I$(SAMMYOSROOT)/kernel/include
CFLAGS = -g -std=gnu99 -ffreestanding -Wall -Wextra -O0 $(INCLUDE)
LINKER_FLAGS = -ffreestanding -O0 -nostdlib -nostdinc
