
ifndef SAMMYOSROOT
    $(error Please run ". envsetup.sh" from the sammyos root directory)
endif

ifndef SAMMYOSARCH
    $(error Please run ". envsetup.sh" from the sammyos root directory)
endif

BUILD_DIR = ${SAMMYOSROOT}/_out

INCLUDE = -I$(SAMMYOSROOT)/libc/include -I$(SAMMYOSROOT)/kernel/include
CFLAGS = -g -std=gnu99 -ffreestanding -Wall -Wextra -O0 $(INCLUDE)
LINKER_FLAGS = -ffreestanding -O0 -nostdlib -nostdinc
